# Generated by Django 4.1.4 on 2023-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
