# Generated by Django 4.1.4 on 2023-11-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_user_alter_transaction_details_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category_id',
            new_name='product_category',
        ),
    ]
