# Generated by Django 4.1.4 on 2023-11-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_address_info_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_items',
            old_name='product_id',
            new_name='product',
        ),
    ]
