# Generated by Django 4.1.4 on 2023-11-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_product_order_items_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice',
            field=models.CharField(choices=[('seller', 'seller'), ('company', 'company')], default='user', max_length=7),
        ),
    ]
