# Generated by Django 4.1.4 on 2023-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.CharField(choices=[('seller', 'seller'), ('company', 'company')], default='user', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
