# Generated by Django 4.1.4 on 2023-11-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_category',
            new_name='Post_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
