# Generated by Django 4.1.4 on 2023-11-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_job_category_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='job_category_id',
            new_name='Post_category_id',
        ),
    ]
