# Generated by Django 4.1.4 on 2023-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='product_multi_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_multi_image'),
        ),
    ]
