# Generated by Django 4.1.4 on 2023-11-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_post_image_alter_product_multi_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_multi_image',
            name='product_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
