# Generated by Django 4.1.4 on 2023-11-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_product_multi_image_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
    ]
