# Generated by Django 4.1.4 on 2023-11-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_user_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
