# Generated by Django 4.1.4 on 2023-11-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_user_id_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post_category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product_multi_image',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction_details',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='transaction_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='address_info',
        ),
        migrations.DeleteModel(
            name='Job_category',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='order_items',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='Post_category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
        migrations.DeleteModel(
            name='product_multi_image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='transaction_details',
        ),
    ]
