# Generated by Django 4.1.4 on 2023-11-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_job_application_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobs'),
        ),
    ]
