# Generated by Django 4.1.4 on 2023-11-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_job_application_job_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_application',
        ),
    ]
