# Generated by Django 4.1.4 on 2023-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.FileField(default=0, upload_to='disabled_certificate'),
            preserve_default=False,
        ),
    ]
