# Generated by Django 4.1.4 on 2023-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
