# Generated by Django 4.1.4 on 2023-12-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_message_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
