# Generated by Django 4.1.4 on 2023-12-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_message_receiver_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction_details',
        ),
    ]
