# Generated by Django 5.0 on 2024-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_order_created_at_alter_order_items_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=0, upload_to='user'),
        ),
    ]
